In [36]:
import tensorflow as tf

In [18]:
print(tf.add(1,2))
print(tf.add([1,2],[3,4,]))
print(tf.reduce_sum([1,2,3,4]))
print(tf.square(3))

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([4 6], shape=(2,), dtype=int32)
tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)


In [24]:
x = tf.matmul([[1],[2]], [[2,3]])
print(x)
print(x.shape)
print(x.dtype)

tf.Tensor(
[[2 3]
 [4 6]], shape=(2, 2), dtype=int32)
(2, 2)
<dtype: 'int32'>


In [28]:
import numpy as np

ndarray = np.ones([3,3])

print("Tensorflow operations convert numpy to tensors automatically")
tensor = tf.multiply(ndarray, [[42]])
print(tensor)

Tensorflow operations convert numpy to tensors automatically
tf.Tensor(
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]], shape=(3, 3), dtype=float64)


In [37]:
x = tf.random.uniform([3,3])

print(tf.config.experimental.list_physical_devices())

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'), PhysicalDevice(name='/physical_device:XLA_CPU:0', device_type='XLA_CPU')]


In [38]:
import time

def time_matmul(x):
    start = time.time()
    for loop in range(10):
        tf.matmul(x,x)
    result = time.time() - start
    print("10 loops: {:0.2f}ms".format(1000*result))
    

print('With CPU')
with tf.device("CPU:0"):
    x = tf.random.uniform([1000, 1000])
    assert x.device.endswith("CPU:0")
    time_matmul(x)
    
print('With XLA_CPU')
with tf.device("XLA_CPU:0"):
    x = tf.random.uniform([1000, 1000])
    assert x.device.endswith("XLA_CPU:0")
    time_matmul(x)


With CPU
10 loops: 157.53ms
With XLA_CPU


ValueError: Unknown attribute: 'XLA_CPU' in 'XLA_CPU:0'

In [45]:
ds_tensors = tf.data.Dataset.from_tensor_slices([1,2,3])

import tempfile
_, filename = tempfile.mkstemp()

with open(filename, 'w') as f:
    f.write("Line 1\n"
           "Line 2\n"
           "Line 3\n")
    
ds_file = tf.data.TextLineDataset(filename)

## Apply transformations

In [46]:
ds_tensors = ds_tensors.map(tf.square).shuffle(2).batch(2)
ds_file = ds_file.batch(2)

In [49]:
for x,y in tf.data.Dataset.zip((ds_tensors, ds_file)):
    print(x,y,)

tf.Tensor([1 9], shape=(2,), dtype=int32) tf.Tensor([b'Line 1' b'Line 2'], shape=(2,), dtype=string)
tf.Tensor([4], shape=(1,), dtype=int32) tf.Tensor([b'Line 3'], shape=(1,), dtype=string)
