In [2]:
import tensorflow as tf
import tensorflow.keras as keras
import matplotlib.pyplot as plt
import numpy as np

## Build a simple model

### Sequential model

In [13]:
model = keras.models.Sequential([
    keras.layers.Dense(64, activation=tf.nn.relu),
    keras.layers.Dense(64, activation=tf.nn.relu),
    keras.layers.Dense(10, activation=tf.nn.relu),
])

In [14]:
model(tf.random.uniform((1, 27, 27)))

<tf.Tensor: shape=(1, 27, 10), dtype=float32, numpy=
array([[[0.        , 0.3004715 , 0.        , 0.        , 0.15087141,
         0.        , 0.        , 0.        , 0.        , 0.05651395],
        [0.        , 0.22220892, 0.08895078, 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.24145389],
        [0.1510152 , 0.15075141, 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.04780481],
        [0.        , 0.30998278, 0.17683925, 0.02288278, 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.18725622],
        [0.23144355, 0.16289295, 0.        , 0.        , 0.10691127,
         0.        , 0.        , 0.        , 0.        , 0.06305408],
        [0.1870251 , 0.        , 0.00768808, 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.23191014],
        [0.        , 0.35319713, 0.11040099, 0.00990458, 0.        ,
         0.        , 0.        , 0.        ,

In [31]:
dense_l1 = keras.layers.Dense(10, kernel_regularizer=tf.keras.regularizers.l1(0.01))
dense_l2 = keras.layers.Dense(10, kernel_regularizer=tf.keras.regularizers.l2(0.01))


dense_l1.build([10,10])
dense_l2.build([10,10])
tf.reduce_mean(dense_l1.weights[0] - dense_l2.weights[0])


<tf.Tensor: shape=(), dtype=float32, numpy=-0.048088513>

In [64]:
def monitor(inputs):
    print(inputs)
    return inputs

model = keras.models.Sequential([
    # Adds a densely-connected layer with 64 units to the model:
    keras.layers.Dense(64, activation='relu'),
    # Add another:
    keras.layers.Dense(64, activation='relu'),
    # Add an output layer with 10 output units:
    
    keras.layers.Lambda(monitor),
    
    keras.layers.Dense(10)
])

model.compile(optimizer=tf.keras.optimizers.Adam(0.01),
              loss=tf.keras.losses.CategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'],
              run_eagerly=True,
             )

x_data, y_data = tf.random.uniform((10,32)), tf.random.uniform((10,10))
model.fit(x_data, y_data)

tf.Tensor(
[[0.23402834 0.04124551 0.         0.05509746 0.22514695 0.
  0.         0.60115427 0.         0.         0.2792915  0.
  0.3308892  0.2697289  0.         0.21721137 0.         0.14090008
  0.         0.         0.17558903 0.         0.         0.
  0.         0.13900419 0.         0.358423   0.43707734 0.3216212
  0.2180453  0.         0.         0.05564057 0.00278605 0.22161616
  0.         0.         0.28187323 0.         0.         0.
  0.         0.54319644 0.41100347 0.         0.         0.3058873
  0.         0.12068892 0.         0.32616428 0.         0.10455557
  0.         0.03435132 0.         0.15975396 0.28451455 0.29800448
  0.         0.06673204 0.         0.        ]
 [0.20096336 0.         0.         0.         0.16700833 0.
  0.16673125 0.45941526 0.         0.         0.5368464  0.
  0.21329904 0.20491949 0.         0.47608945 0.         0.43495613
  0.         0.         0.40119687 0.         0.         0.24218461
  0.         0.         0.         0.386

## Complex models